// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChPelHAitEsskbIWDcDlWFCsv2qwpoikk',
    appId: '1:89367147471:web:1da3eba1db1cc2a2e598ba',
    messagingSenderId: '89367147471',
    projectId: 'qr-code-b3cd8',
    authDomain: 'qr-code-b3cd8.firebaseapp.com',
    storageBucket: 'qr-code-b3cd8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1ihg6uqokfIWFKYwXiArMG_UbZ13xGzk',
    appId: '1:89367147471:android:ba35a07e3e344ba7e598ba',
    messagingSenderId: '89367147471',
    projectId: 'qr-code-b3cd8',
    storageBucket: 'qr-code-b3cd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMVf0mufTaaqMdmmDWgd_U47zZk1KYSOk',
    appId: '1:89367147471:ios:b5998b11b43468dae598ba',
    messagingSenderId: '89367147471',
    projectId: 'qr-code-b3cd8',
    storageBucket: 'qr-code-b3cd8.appspot.com',
    iosBundleId: 'com.example.qrCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMVf0mufTaaqMdmmDWgd_U47zZk1KYSOk',
    appId: '1:89367147471:ios:ec3ced94c8e97515e598ba',
    messagingSenderId: '89367147471',
    projectId: 'qr-code-b3cd8',
    storageBucket: 'qr-code-b3cd8.appspot.com',
    iosBundleId: 'com.example.qrCode.RunnerTests',
  );
}
